FROM node:10.16.3-stretch

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY /src ./src
COPY /config ./config
COPY tsconfig.json .
EXPOSE 3000
CMD [ "npm", "run", "dev" ]
